name: mhg_flutter
description: A new Flutter project.

version: 1.3.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  html: any
  intl: any
  mongo_dart: any
  path_provider: any
  shared_preferences: any
  simple_auth_flutter: any
  simple_auth: any
  sqflite: any
  url_launcher: any
  flutter_cache_store: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
